### ISSUE TITLE
Install DIGITs

### ISSUE THREAD

**Issue by efwright** [mferrato/CISC489-Project-Machine-Learning#2]
Install digits and run samples.
https://developer.nvidia.com/digits

**Comment by mferrato** [comment]
Working on this now

**Comment by mferrato** [comment]
Was able to set up Docker and a Docker Image of Nvidia DIGITS on my computer. The DIGITS image is working but it shows two errors. It fails to initialize libdc1394 because I do not have a camera on my personal laptop and it it shows a CudaRunTimeGetVersion() error #35. This is because I have no NVIDIA CUDA driver installed on my computer because the CUDA toolkit is 6 GB of memory and I have no space. So it seems that it will be impossible to set it up on my personal pc.

I tried to set up the Docker Image on our research lab server VADER, but I'm not a member of the sudoers list and I don't have permission to pull the image. I'm going to have to submit a ticket to the EECIS service desk.

**Comment by mferrato** [comment]
Digits is installed and ready to use on the research lab server.
